### ISSUE TITLE
Couleurs secondaires et logo

### ISSUE THREAD

**Issue by chblw** [dot-layer/brand-identity#2]
Hello, 

J'utilise les couleurs secondaires (beige, rouge et jaune) pour des diapositives. Avec le logo de .Layer en bas des diapos, est-ce que je devrais utiliser le logo en couleur ou en noir et blanc ? Voici un apperçu en couleur. 

![image](https://user-images.githubusercontent.com/33635178/56069764-82858280-5d52-11e9-97eb-0a0b63a0df1a.png)

**Comment by chblw** [comment]
J'aurais aussi besoin de votre input pour la couleur des hyperlink. J'ai mis le bleu .Layer mais on dirait que le cyan est mieux car c'est la convention. 

![image](https://user-images.githubusercontent.com/33635178/56428593-f4e3ee80-628d-11e9-9793-e0ba619dd519.png)

**Comment by stecaron** [comment]
Moi j'aime bien ... toi @jcyelle ?

**Comment by stecaron** [comment]
J'aime les deux bulllets points aussi @chblw !

**Comment by jcyelle** [comment]
le vert sur blanc est peut-être dur à lire un peu.. je laisserais le texte noir et si tu veux donner de l'importance à cette section tu pourrais faire un encadré en outline avec le vert ''DotLayer''.. ou sinon en cyan

si ça enlève trop de vert tu pourrais remplacer ta bande jaune dans le bas par le vert!

**Comment by chblw** [comment]
Merci pour les inputs @jcyelle @stecaron !

Je vais le laisser en cyan car c'est la convention des hyperlink. 

J'aime l'idée d'avoir plus de vert, alors j'ai remplacé le jaune. Bien que le rouge + jaune allait bien ensemble, je trouve mieux de mettre plus de vert parce que c'est notre couleur primaire. 

![image](https://user-images.githubusercontent.com/33635178/56542917-ea4f8080-653d-11e9-8a2e-7bf08ad6fe13.png)

**Comment by jcyelle** [comment]
@chblw très nice comme ça ouais!

**Comment by stecaron** [comment]
Très fort @chblw !

**Comment by stecaron** [comment]
C'est un peu hors-contexte mais PTI @chblw j'ai utiliser le logo, le vert de .Layer pour les contour de box et le noir pour les titres dans notre poster de GLO-7030 (en utilisant le template de GRAAL). Ça donne quelque chose comme ça (j'aime bien):

<img width="1123" alt="Screen Shot 2019-04-22 at 8 41 33 PM" src="https://user-images.githubusercontent.com/29443824/56543370-48309800-653f-11e9-8787-8b6f3133a112.png">

**Comment by chblw** [comment]
Ouain @stecaron vu que tu vas avoir des images, on veut diriger l'attention vers les images et non les titres, ça fait du sens. Dans les slides je mets de l'emphase sur les titres. 

On pourrait mettre des templates officiels dans ce repo plus tard !
